export const data = [
  {
    roll: "IIT2018040",
    name: "Manthan Surkar",
    github: "thesmallstar",
    score: {
      webd: 100,
      foss: 50,
      cybersec: 20,
      CC: 50,
      appd: 30,
      ai: 20,
      design: 30,
    },
    sum: 300,
  },
  {
    roll: "IIT2018043",
    name: "Abhishek Singh",
    github: "thesmallabhishek",
    score: {
      webd: 20,
      foss: 50,
      cybersec: 20,
      CC: 50,
      appd: 30,
      ai: 20,
      design: 30,
    },
    sum: 280,
  },
  {
    roll: "IIT2018045",
    name: "Mohanty",
    github: "thesmallmohanty",
    score: {
      webd: 20,
      foss: 50,
      cybersec: 0,
      CC: 50,
      appd: 30,
      ai: 20,
      design: 30,
    },
    sum: 290,
  },
  {
    name: "cheena",
    roll: "IIT2018042",
    github: "thesmallstars",
    score: {
      webd: 20,
      foss: 50,
      cybersec: 0,
      CC: 50,
      appd: 3,
      ai: 20,
      design: 30,
    },
    sum: 260,
  },
  {
    roll: "IIT2018087",
    name: "mishra",
    github: "thesmall",
    score: {
      webd: 20,
      foss: 0,
      cybersec: 0,
      CC: 50,
      appd: 30,
      ai: 20,
      design: 30,
    },
    sum: 50,
  },
];
